### ISSUE TITLE
Changes need to be made to scripts to make it compatible with SSI Data Dashboard module

### ISSUE THREAD

**Issue by priyankasingh** [softwaresaved/visualisation#25]
Hi Mike,

I have made following changes to your scripts to make it work with SSI Data Dashboard module. Please make these changes on your end, so you can maintain it and improve it in the future. Then we won't have to make any changes manually in our end.

These are the changes I made to your script:

1. run_ingest.sh

Since, this script is run on crontab on virtual machine, it doesn't use browser, so it can't use browser for authentication. We changed line no 15-17 in the shell script to fix this issue. 

``` 
python src/download_consultancy.py --noauth_local_webserver

python src/download_swc.py --noauth_local_webserver

python src/download_policy.py --noauth_local_webserver 
```

2. pie.js in js directory

Earlier users were calling the javascripts directly from the html webpage. We changed it to use html 'div' tag with class name 'ssivis-pie' instead. The javascript is invoked for every instance of this class. Users can now pass attributes from the 'div' to javascript. Users can pass the bound limit for the pie chart. The colour for the pie chart is now fixed.
So, the 'get_slice_colour' function is changed to incorporate these changes. Please view this file to see the changes we made: [pie.js](https://github.com/softwaresaved/ssiwebmod_data_dashboard/blob/master/js/pie.js)

It can be used in the data dashboard page type like this:

``` 
<div bound="1,2,5,10,15,20" class="ssivis-pie" data_file="funders_effort.csv" height="400" id_tag="pieFunderEffort" label_column="Funder" value_column="Effort" width="500">&nbsp;</div>

<div class="pie" id="pieFunderEffort">&nbsp;</div>
```

3. barchart.js

Same as above, the barchart.js file is not called directly. Instead it uses html 'div' tag 'ssivis-bar'. It embeds the barchart at every instance of the div. Please see [barchart.js](https://github.com/softwaresaved/ssiwebmod_data_dashboard/blob/master/js/barchart.js). It can be used in the data dashboard page type like this:

```
<div class="ssivis-bar" data_file="funders_effort.csv" height="400" id_tag="chartFunderEffort" label_column="Funder" value_column="Effort" width="500">&nbsp;</div>

<div class="barchart" id="chartFunderEffort">&nbsp;</div>
```

4. Readme.md

When I was running the run_ingest script, we had some issue with google authentication. Maybe, you can include this step in your documentation too. Please see the [following page](https://github.com/softwaresaved/ssiwebmod_data_dashboard_ingest#configuring-the-visualisation-repository) to see how we solved the authentication problem.

Please let me know how you want to include these changes. I can ask for the push permission to your repo and make the changes myself or you can do it.

Let me know if you have any questions.

Thanks.
Priyanka

**Comment by mikej888** [comment]
Notes on experiences in using barchart.js with html/consultancy/funders.html

funders.html updated with the required `div` tag:
```
<div class="ssivis-bar" data_file="sheets/as-is/funders_effort.csv" height="400" id_tag="chartFunderEffort" label_column="Funder" value_column="Effort" width="500">&nbsp;</div>
```
barchart.js currently does:
```
var data_file = '../data/' +  div_element.attr('data_file');
```
Having such hard-coded paths undoes the work done to make the JavaScript generic and reusable. barchart.js should get the file path, including `"../data/"`, from the HTML i.e.
```
var data_file = div_element.attr('data_file');
```
Using this approach, the `div` tag for funders.html would be:
```
<div class="ssivis-bar" data_file="../data/sheets/as-is/funders_effort.csv" height="400" id_tag="chartFunderEffort" label_column="Funder" value_column="Effort" width="500">&nbsp;</div>
```

**Comment by mikej888** [comment]
There is a missing reference in barchart.js. When viewing viewing an HTML page that imports this script, Chrome's developer tools shows the error:
```
barchart.js:178 Uncaught ReferenceError: jQuery is not defined
```
This corresponds to the final lines in barchart.js:
```
})(jQuery);
```
This can be fixed by adding 
```
<script src="../../js/jQuery.js"></script>
```
to funders.html.

**Comment by mikej888** [comment]
I added
```
console.log(data_file);
```
to check that the div element was being extracted and parsed but there was no output. Moving JavaScript imports under the `<div>` tag in funders.html sorted this.
```
<script src="../../js/jQuery.js"></script>
<script src="../../js/d3.min.js"></script>
<script src="../../js/pie.js"></script>
<script src="../../js/barchart.js"></script>
```
(but I like the imports at the top so this doesn't seem clean to me!)

**Comment by mikej888** [comment]
Having tried the above changes, Chrome Developer tools now showed:
```
[div.ssivis-bar, context: div.ssivis-bar]
barchart.js:44 ../../data/sheets/as-is/funders_effort.csv
jQuery.js:9175 POST http://localhost:8000/data/sheets/as-is/funders_effort.csv 501 (Unsupported method ('POST'))
```
This seems to be due to the line
```
$.post(data_file, function() {
```
[post](https://api.jquery.com/jquery.post/) loads data from a server using an HTTP POST request. The simple Python web server I use for development, `python -m http.server`, does not support POST. This would require writing some custom Python.

GitHub gh-pages does not support POST requests either. 

To ingest this change would mean that the visualisations scripts would become a lot less flexible, being unusable with GitHub gh-pages and simple web servers.

**Comment by mikej888** [comment]
A possible solution is that, instead of editing barchart.js and pie.js and adding your wrapper function round the `draw_` functions in those files, you create two new JavaScript files with your wrapper functions that call out to these `draw_` functions. In that way the same `draw_` functions could continue to be used as at present (without using jQuery post) but can be used also within your Drupal plugin.

Also, the change to the data_file path and use of `"../data/"+` would then no longer be an issue.

**Comment by mikej888** [comment]
Updated https://github.com/softwaresaved/visualisation/blob/gh-pages/README.md, both gh-pages and staging branches, with your enhanced information on Google Authentication.

Also updated run_ingest.sh to use the --noauth_local_webserver flag.

**Comment by mikej888** [comment]
I think I've a solution. Rename your barchart.js to barchart-drupal.js (for example) with your function:

```
(function ($) {

    $('.ssivis-bar').each(function() { // This will find each use of ssivis-bar, get csv file name and populate the table
        var div_element = $(this);

	// get csv file from data attribute
        var data_file = '../data/' +  div_element.attr('data_file');
        var id_tag =  div_element.attr('id_tag');
        var label_column = div_element.attr('label_column');
        var value_column = div_element.attr('value_column');
        var width = div_element.attr('width');
        var height = div_element.attr('height');

	//console.log(data_file, id_tag, label_column, value_column, width, height);

        $.post(data_file, function() {

            try{
		//console.log(data_file, id_tag, label_column, value_column, width, height);
		draw_bar(data_file, id_tag, label_column, value_column, width, height); 
            }
            catch(err) {
                console.log(err);
            }
        });
    });

})(jQuery);
```
Note how my draw function is no longer enclosed. Now import both scripts wherever you import them e.g. if importing within HTML do:
```
<script src="../../js/barchart.js"></script>
<script src="../../js/barchart-drupal.js"></script
```
The above will then call out to `draw_bar` in barchart.js. Despite not having a working `post` function I did a test by putting a call to `draw_bar` before the `$.post` call and putting a `console.log("TEST")` call within `draw_bar` and adding the above two imports to my HTML. The `console.log` call was invoked.

I'll update `draw_chart` in barchart.js and and pie.js with the changes you made to those functions.

**Comment by mikej888** [comment]
barchart.js and pie.js now updated in staging branch:

* barchart.js: draw_chart renamed to draw_bar.
* pie.js: draw_chart renamed to draw_pie, defines fill_colour array.

**Comment by mikej888** [comment]
pie.js draw_pie no longer needs bounds as it uses an HSV colour scheme.

**Comment by mikej888** [comment]
Please let me know if the foregoing idea for modularisation (https://github.com/softwaresaved/visualisation/issues/25#issuecomment-330825582) is OK? If so this ticket can be closed as the rest has been done.

**Comment by steve-crouch** [comment]
This looks like a solid approach to me - I'll ask @priyankasingh to comment.

**Comment by priyankasingh** [comment]
Hi Mike,

Thanks for making all the changes. I added the js wrapper to make it work with your modified script. I have tested it and it's all working fine.

I will close the ticket.

Priyanka

**Comment by mikej888** [comment]
@priyankasingh, cool, glad it works fine :-)
