### ISSUE TITLE
Visualise carpentry instructors in the UK

### ISSUE THREAD

**Issue by ctmartins** [softwaresaved/visualisation#29]
Spreadsheet with instructors: 
https://drive.google.com/open?id=1Yi7SGspMfFB2cKk_M47a4aldHIJxxUc94LKwpJ2mVg8

- Tab: carpentry_instructors
- Visualisation: Number of instructors per affiliation
- Range: A1:L119
- Type of visualisation: pie chart, bar chart and circle packing

**Comment by mikej888** [comment]
carpentry_instructors tab contains raw data. This would need post-processing in Python or JavaScript to get the Number of instructors per affiliation. The Number of instructors per affiliation needs to be provided as a tab in your spreadsheet. It should look like instructors_airports (that tab is in a good format for use with the visualisation scripts).

**Comment by ctmartins** [comment]
Use this spreadsheet instead:
https://docs.google.com/spreadsheets/d/1-tfDUusAIs5clffqDpsHsncn7-W47-UC-TepG3xTlwU/edit?usp=sharing

Tab: instructors-affiliation_GB_2017-12-14
Range: A1:B42 (including header)

**Comment by mikej888** [comment]
Commited updates, see http://localhost:8000/html/training/swc_instructors_2017.html.

I used a horizontal bar chart so the text is readable. Making the pie chart text readable involves work in the pie chart code in general, which may be non-trivial (it's already an issue, #4).
