### ISSUE TITLE
Visualise carpentry workshops in the UK

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/visualisation#30]
Spreadsheet with workshops: 
https://drive.google.com/open?id=1Od0cTQ2KPivaj6r_18RBD79lIo3yokUw9fks2RT8mOI

- Tab: carpentry_workshops
- Visualisation: Number of workshops per affiliation
- Range: A1:W145
- Type of visualisation: pie chart, bar chart and  #circle packing

**Comment by mikej888** [comment]
carpentry_workshops tab contains raw data. This would need post-processing in Python or JavaScript to get the Number of workshops per affiliation. The Number of workshops per affiliation needs to be provided as a tab in your spreadsheet. Is this not the same as the workshop_institution tab? (that tab is in a good format for use with the visualisation scripts).

**Comment by ctmartins** [comment]
Use this spreadsheet instead:
https://docs.google.com/spreadsheets/d/1-tfDUusAIs5clffqDpsHsncn7-W47-UC-TepG3xTlwU/edit?usp=sharing

Tab: workshops-affiliation_GB_2017-12-14
Range: A1:B38 (including header)

**Comment by mikej888** [comment]
Commited updates, see 
 http://softwaresaved.github.io/visualisation/html/training/swc_workshops_2017.html.

I used a horizontal bar chart so the text is readable. Making the pie chart text readable involves work in the pie chart code in general, which may be non-trivial (it's already an issue, #4).
